services:
  db:
    image: mysql:8.4.4
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_HOST=%
      - MYSQL_DATABASE=charmtong
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "3308:3306"
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt